### ISSUE TITLE
Create Docker Environment for Device Detector

### ISSUE THREAD

**Issue by cycling777** [w-pinkietech/rpi4-driver#3]
### 🎯 Objective
Create Docker environment for the privileged Device Detector container with proper udev and Redis access.

### 📋 Scope
- Create `device-detector/Dockerfile` for privileged container
- Create `docker-compose.yml` for Redis + Device Detector services
- Ensure proper device access and privilege configuration
- Add container health checks

### 🔧 Technical Requirements
- **Privileged Access**: Container needs udev access (`--privileged` or specific devices)
- **Redis Connection**: Container must connect to Redis service
- **Minimal Image**: Use slim Python base image
- **Security**: Minimize attack surface despite privileged access

### ✅ Acceptance Criteria
- [ ] Dockerfile builds successfully
- [ ] Container can access udev events
- [ ] Container connects to Redis
- [ ] docker-compose.yml starts both services
- [ ] Health checks verify service status
- [ ] Volume mounts work for udev access

### 📝 Implementation Details
```dockerfile
FROM python:3.11-slim
# Minimal dependencies for udev access
# Copy source code and requirements
# Set proper entrypoint
```

```yaml
# docker-compose.yml
services:
  redis:
    image: redis:alpine
  device-detector:
    build: ./device-detector
    privileged: true
    depends_on: [redis]
```

### 🔗 Related
- Parent Epic: #1
- Depends on: #2 (Device Detector Core Logic)

This enables the privileged container to run in production environment.
